### ISSUE TITLE
StyleColor flag [GUI.Col_TextDisabled] not responding to disable text in GUI:BeginMenu()

### ISSUE THREAD

**Issue by mushroom8009** [MINIONBOTS/FFXIVMinion#101]
GUI:PushStyleColor(GUI.Col_TextDisabled)
GUI:BeginMenu(str,false)
before 7.0, it was response, but no longer

![image](https://github.com/MINIONBOTS/FFXIVMinion/assets/63469413/020f8604-2c21-47c9-acb3-3c52783f25a8)

**Comment by MINIONBOTS** [comment]
![344655067-7b27bfac-a0d8-4ad8-bb4f-29eaee54d258](https://github.com/MINIONBOTS/FFXIVMinion/assets/2842405/5f82384d-a1c5-4f71-9f9f-fbd3d5ed12df)

This works fine for me as you can see. GUI.Col_TextDisabled is changing the color of GUI:TextDisabled("...") elements.
In your example above you just create a BeginMenu / EndMenu. That is most likely not Col_TextDisabled but some other enum value ?
If I had to take a guess, Col_MenuBarBg or Col_Header ?

**Comment by mushroom8009** [comment]
Col_MenuBarBg
![image](https://github.com/MINIONBOTS/FFXIVMinion/assets/63469413/c9919dfb-585a-4efb-89d2-83805112f864)
Col_Header
![image](https://github.com/MINIONBOTS/FFXIVMinion/assets/63469413/6701755a-9601-46ea-b828-43437fe248f5)

use GUI.Col_Text
![image](https://github.com/MINIONBOTS/FFXIVMinion/assets/63469413/c6a184eb-d415-4ccd-847b-ed5ba16dd355)
![image](https://github.com/MINIONBOTS/FFXIVMinion/assets/63469413/19f2c760-1f54-4544-af57-8f4a1d828612)
wiki
![image](https://github.com/MINIONBOTS/FFXIVMinion/assets/63469413/bd2feb51-30dc-4bb4-9d12-8600f2b1620f)

first of all, please you should know that until 6.x, the color was changed by GUI.Col_TextDisabled
i thought from the wiki that this item had an enable/disable attribute and the text in it was the same attribute as TextDisabled
and it did indeed
if you're saying that the specs have changed since 7.0, i agree
however, if it can no longer do what it used to be able to do, it is normal to consider it a issue

if this is a specification, please Close this
sorry to take up your time :)

**Comment by MINIONBOTS** [comment]
Ahhh now I get what you wanted todo originally. 
Have you tried the normal Col.Text ?
We upgraded the imgui version from a very old one to the 'newest', that indeed came with quite a lot of changes.
