### ISSUE TITLE
strange for GetMouseInWorldPos() in Player.localmapid 506 , 589 ,  591 , 590

### ISSUE THREAD

**Issue by mushroom8009** [MINIONBOTS/FFXIVMinion#108]
the cursor is at the feet of the target, although it is hard to see because the cursor is not in the picture
![image](https://github.com/MINIONBOTS/FFXIVMinion/assets/63469413/697528b7-6522-463c-b05e-4f0b96cc5cc6)
i had no problem with other duty, but only LoVM has wrong values
i noticed it when it was reported to me
idk when it started
at least since 7.0

seems to have something to do with the Player pos
im using it in addon and would appreciate it if could fix it as soon as possible....

**Comment by MINIONBOTS** [comment]
I fixed it :)
