### ISSUE TITLE
Can we get documentation for events

### ISSUE THREAD

**Issue by llmmo** [MINIONBOTS/FFXIVMinion#21]
Regarding 

````
-- Registering the Events
RegisterEventHandler("Gameloop.Update",mymodule.OnUpdateHandler) -- the normal pulse from the gameloop
RegisterEventHandler("MYMODULE.TOGGLE", mymodule.ToggleRun) -- the function that gets called when our button is pressed
RegisterEventHandler("Module.Initalize",mymodule.ModuleInit) -- the initialization function, gets called only once at startup of the game
````

What other events are there?

**Comment by MINIONBOTS** [comment]
Heyho,

just those two:
Gameloop.MeshReady
Gameloop.OffMeshConnectionReached

You can also fire your own events from lua ...I would have to lookup the 
command for it , in case you need it.

cheers

Am 09.07.2015 um 19:06 schrieb llmmo:
>
> Regarding
>
> |-- Registering the Events
> RegisterEventHandler("Gameloop.Update",mymodule.OnUpdateHandler) -- the normal pulse from the gameloop
> RegisterEventHandler("MYMODULE.TOGGLE", mymodule.ToggleRun) -- the function that gets called when our button is pressed
> RegisterEventHandler("Module.Initalize",mymodule.ModuleInit) -- the initialization function, gets called only once at startup of the game
> |
>
> What other events are there?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MINIONBOTS/FFXIVMinion/issues/21>.
>


-- 
Stefan Karsten
Raving Lunatic Software Sp. z o.o.
Os. B. Smialego 33/3
60-682 Poznan
M:+48 786817654

**Comment by llmmo** [comment]
Simple enough - thanks
