### ISSUE TITLE
GUI issue

### ISSUE THREAD

**Issue by mushroom8009** [MINIONBOTS/FFXIVMinion#87]
GUI.Col_TextDisabled is not responding in GUI:PushStyleColor()

**Comment by mushroom8009** [comment]
Shortcut Manager
Toggle GUI is not work

**Comment by MINIONBOTS** [comment]
Only 1 problem per issue please. ToggleGUI is fixed.

**Comment by MINIONBOTS** [comment]
![grafik](https://github.com/MINIONBOTS/FFXIVMinion/assets/2842405/7b27bfac-a0d8-4ad8-bb4f-29eaee54d258)
GUI.Col_TextDisabled in GUI:PushStyleColor() , works fine for me. 
Open it again if you see this still not working.
