### ISSUE TITLE
GUI:ListBoxHeader crashes

### ISSUE THREAD

**Issue by xSalice** [MINIONBOTS/FFXIVMinion#90]
GUI:ListBoxHeader crashes

**Comment by MINIONBOTS** [comment]
![grafik](https://github.com/MINIONBOTS/FFXIVMinion/assets/2842405/696df0b5-0abf-46c9-9be7-6ff5dc23ee13)

works fine

**Comment by xSalice** [comment]
GUI:PushItemWidth(10000) before would crash it
