### ISSUE TITLE
Key Binds: Unable to bind F13-F24 anymore

### ISSUE THREAD

**Issue by KaliMinion** [MINIONBOTS/FFXIVMinion#94]
A user reported this to me, forwarding it here.

"Are the binds for minion itself being weird? I used to be able to bind f13 to f24 but doesn't seem like it likes it now."

If I had to guess, the list is just missing the virtual keys for F13-F24, for w/e it comes time to do low priority stuff here is the list.

![image_2024-06-29_141222113](https://github.com/MINIONBOTS/FFXIVMinion/assets/33697905/0b846b4b-dc5a-494c-9518-52f45a1c51b0)

**Comment by MINIONBOTS** [comment]
added support for this, should go out with next dat update
