### ISSUE TITLE
Player Mount Speed only works backwards

### ISSUE THREAD

**Issue by KaliMinion** [MINIONBOTS/FFXIVMinion#99]
Player:GetSpeed() reflects the correct value you set, but it only works when moving backwards, you still move forwards at normal speed.

**Comment by KaliMinion** [comment]
Speed walking is back with using Reset Speed

![image_2024-06-30_151737625](https://github.com/MINIONBOTS/FFXIVMinion/assets/33697905/c3964f79-3070-4277-a4d3-378f3c335f0b)

**Comment by MINIONBOTS** [comment]
Sorry, can you please elaborate that in a way so my brain can understand it ? Do you SET any of these values to something else and then this Player:GetSpeed() gives back wrong values ? or what exactly do you mean.
